### ISSUE TITLE
[Question] Cyclic dependencies

### ISSUE THREAD

**Issue by frabnt** [stemmlerjs/ddd-forum#34]
After generating a graph of module deps, I noticed these circular dependencies:

1. src/modules/forum/domain/member.ts > src/modules/forum/domain/events/member-created.ts
2. src/shared/domain/aggregate-root.ts > src/shared/domain/events/domain-events-manager.ts
3. src/modules/users/domain/user.ts > src/modules/users/domain/events/user-created.ts

This obviously breaks the **acyclic dependency principle**.

@stemmlerjs Is this somehow acceptable from your POV?

**Comment by stemmlerjs** [comment]
@frabnt I don't think there's a cycle there.
