### ISSUE TITLE
Can't sign up to DDDForum.com

### ISSUE THREAD

**Issue by aashir-khan** [stemmlerjs/ddd-forum#42]
When I try to create an account and press the submit button on dddforum.com. I get the following error:

![image](https://user-images.githubusercontent.com/25349581/103720330-1d97a480-4f99-11eb-9208-005f60b75a8b.png)

**Comment by stemmlerjs** [comment]
Hey @aashir-khan, were you able to get your database instance up and running here (https://github.com/stemmlerjs/ddd-forum/issues/42)?

**Comment by aashir-khan** [comment]
A note that the above picture is from the production instance (https://dddforum.com/) and not localhost. However when I try on my local instance, it works fine to sign up and I don't get that error

**Comment by aashir-khan** [comment]
I tried in my local instance to sign up with the same email, username, and password again (after being able to register successfully) and then I got that `res.status` error but looking through the usecase and controller for creating a user, seems like we handle existing email and username scenarios fine

**Comment by stemmlerjs** [comment]
@aashir-khan ah yes - just issued a fix for that https://github.com/stemmlerjs/ddd-forum/pull/44.

Thank you!
