### ISSUE TITLE
Controller validation with Joi

### ISSUE THREAD

**Issue by qasimalbaqali** [stemmlerjs/ddd-forum#50]
I've been trying to follow this repositories way of doing things, and I have to say it's blowing my mind on how sleek this implementation is. I noticed that there is no proper validation of the HTTP request data such as using `Joi` or `yup`.

I know that there is a validation mechanism in the UseCase class `CreateUserUseCase.ts` when creating the ValueObjects, but I felt like there needs to be one layer of validation in a higher level of the architecture which sits near the Infrastructure Layer (most outer layer).

I tried to implement it in my project using ddd-forum structure, and I would like anyone's opinion in the implementation if it makes sense and is the correct way of doing things.

`shared/core/AppError.ts`

```js
....

export class ValidationError extends Result<UseCaseError> {
  public constructor(error: any) {
    super(false, {
      message: `A validation error occured`,
      error: error,
    } as UseCaseError);
    logger.info(`[AppError]: A validation error occured`);
    logger.error(error);
  }
}
```

`shared/core/Validatior.ts`

```js
import Joi from "joi";

import { Result, left, right, Either } from "../../shared/core/Result";
import { ValidationError } from "./AppError";

type ValidationResponse = Either<Result<ValidationError> | Result<any>, Result<void>>;

export class Validator {
  public static async validate(
    schema: Joi.Schema,
    dto: any,
  ): Promise<ValidationResponse> {
    try {
      await schema.validateAsync({ ...dto });
      return right(Result.ok<void>());
    } catch (err) {
      const error: Joi.ValidationError = err;
      return left(Result.fail<void>(error.details[0]["message"])) as ValidationResponse;
    }
  }
}
```

`src/modules/users/useCases/createUser/CreateUserController.ts`

```js
....
async executeImpl(req: DecodedExpressRequest, res: express.Response): Promise<any> {
    let dto: CreateUserDTO = req.body as CreateUserDTO;
    dto = {
      name: TextUtils.sanitize(dto.name),
      email: TextUtils.sanitize(dto.email),
    };

    const validationSchema = Joi.object({
      name: Joi.string().min(2).max(10).strip().required(),
      email: Joi.string().email({ minDomainSegments: 2 }).required(),
    });

    try {
      const validation = await Validator.validate(validationSchema, dto);
      if (validation.isLeft()) {
        const error = validation.value;
        return this.unprocessable(res, error.errorValue());
      }
      ......
  }
....
```

**Comment by Errindel** [comment]
Hey! 

You can also check out [class-validator](https://github.com/typestack/class-validator). It's widely used to handle such cases. For example, NetJS framework is doing DTO validation using it. It is happening right on the level of controllers. It also produces a nice structure of the error out of the box. It has less verbose API than Joi and it's really comfortable to use. You just define a class that has expected properties and decorate each prop with desired validation function. It goes hand in hand with class-serializer witch can be used to serialize data returned from the controller into the expected format.

If you want to take a look some time ago I started to create an app using [NestJS,](https://nestjs.com/) Prisma and many patterns that @stemmlerjs introduced into this repository. 
https://github.com/Meskaria/fast-cards
It's now deprecated as I'm learning more and more bout DDD and what I had there is not the best possible implementation of the domain.

**Comment by qasimalbaqali** [comment]
@Errindel Thank you for sharing your knowledge with me! I will have a look at your Github repo and see how do you tackle the different problems the domain you are working on, could come very handy for me :)

**Comment by Errindel** [comment]
@qasimalbaqali If you want to learn how the DDD principles work in different languages check out these repositories: 
- https://github.com/Creditas/kotlin-ddd-sample
- https://github.com/kgrzybek/modular-monolith-with-ddd
- https://github.com/anton-liauchuk/educational-platform
- https://github.com/BottegaIT/ddd-leaven-v2
- https://github.com/hbendix/domain-driven-nest
- https://github.com/mariuszgil/aggregates-by-example

I cannot recommend more reading the Domain-Driven Design by Eric Evans. In my opinion, the longer form of that book is letting the knowledge sink better than reading through summarized articles about DDD. Good luck on your journey with DDD :)

**Comment by qasimalbaqali** [comment]
@Errindel appreciate it! I reached halfway through the book, and I felt like I needed a practical way to apply it to really ingest all the knowledge it gives. Sometimes I feel like it's a bit abstract for me, so I had to get down and code to better grasp it.
