### ISSUE TITLE
What to do with persistence data if business rules change

### ISSUE THREAD

**Issue by johnwalshuk** [stemmlerjs/ddd-forum#51]
Hi,

An example here is the `PostTitle` value object. It has rules that a title must have a min of `2` and a max of `85`.

Lets say the business decides to change the min to `5` on any new posts.

When we pull existing data from the persistence store any post with a  title that's only 2 characters long will fail when we're converting the raw object in the `PostMapper` to the domain. What should happen here?

**Comment by qasimalbaqali** [comment]
One more thing that is making wonder, this means that the in the mapper the creation of that `ValueObject` will fail. That means the creation of the entity will fail, so how would we propagate the error that is throw from the creation of the `ValueObect` to the `UseCase` or even the `Controller`.
