### ISSUE TITLE
UserId as Value Object || Entity ?

### ISSUE THREAD

**Issue by suchcodemuchwow** [stemmlerjs/ddd-forum#68]
I was wondering why you chose UserId as Entity, i thought throughly and felt a bit more inclined towards UserId should be a ValueObject. And I found couple of articles regarding that:

[3 Reasons to Model Identity as a Value Object](https://buildplease.com/pages/vo-ids/)
[Entity vs Value Object: the ultimate list of differences](https://enterprisecraftsmanship.com/posts/entity-vs-value-object-the-ultimate-list-of-differences/)

Could you please share your opinions, why did you choose Entity ?

**Comment by MSE99** [comment]
I'm wondering about the same thing, come to think of it maybe it's because it would be easier to compare the reference against a user entity by just calling the the user entity `equals` against the `UserId`.
