### ISSUE TITLE
Tooltip should appear over vote options when not logged in

### ISSUE THREAD

**Issue by stemmlerjs** [stemmlerjs/ddd-forum#8]
When the user isn't logged in, if they hover over any of the vote options, a tooltip should appear saying "Want to vote? You need to sign up here". 

The word "here" should link to `/join`.

**Comment by faisol-chehumar** [comment]
PR request submitted

**Comment by stemmlerjs** [comment]
Done-zo! https://github.com/stemmlerjs/ddd-forum/pull/18

Thanks :)
